CREATE DATABASE MAJOR;

USE MAJOR;


CREATE TABLE COMPANY(
	COMPANY_ID INT NOT NULL auto_increment PRIMARY KEY,
    COMPANY_NAME VARCHAR(100)  ,
    CATEGORY varchar(100),
    OVERVIEW TEXT,
    FEATURES TEXT,
    COMPANY_WEBSITE VARCHAR(50),
    RATING INT
);

 -- select * from company;
-- DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
	PRODUCT_ID INT NOT NULL auto_increment PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY varchar(100),
    COMPANY_ID INT NOT NULL , foreign key(COMPANY_ID) references COMPANY(COMPANY_ID),
    PRICE DECIMAL(10,3),
    FEATURES TEXT,
    RATING INT
);

 -- select * from product;
  drop table COMPANY_REVIEW;
 
CREATE TABLE COMPANY_REVIEW(
	CRID INT NOT NULL auto_increment PRIMARY KEY,
    AUTHOR INT NOT NULL, foreign key(AUTHOR) references USER(ID) ON DELETE CASCADE,
    TITLE VARCHAR(400),
    CR_RATING INT, -- GIVEN BY THE USER
    CREATION_DATE datetime NOT NULL,
    COMPANYID INT, foreign key(COMPANYID) references COMPANY(COMPANY_ID) ON DELETE CASCADE,
    ANSWER_1 TEXT,
    ANSWER_2 TEXT,
    ANSWER_3 TEXT,
    ANSWER_4 TEXT
);

-- select * from COMPANY_REVIEW;


CREATE TABLE PRODUCT_REVIEW(
	PRID INT NOT NULL auto_increment PRIMARY KEY,
    AUTHOR INT NOT NULL, foreign key(AUTHOR) references USER(ID) ON DELETE CASCADE,
    TITLE VARCHAR(400),
    PR_RATING INT, -- GIVEN BY THE USER
    CREATION_DATE datetime NOT NULL,
    PRODUCTID INT, foreign key(PRODUCTID) references PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    ANSWER_1 TEXT,
    ANSWER_2 TEXT,
    ANSWER_3 TEXT,
    ANSWER_4 TEXT
);

CREATE TABLE USER(
	ID INT NOT NULL auto_increment PRIMARY KEY,
    USERNAME VARCHAR(100),
    PASSWORD varchar(100) 
);

insert into USER values (1,"Admin","abc123");


-- dropping the constraints to add "On Delete Cascade".
ALTER TABLE PRODUCT
DROP CONSTRAINT product_ibfk_1;

-- for Product Table
ALTER TABLE PRODUCT
ADD CONSTRAINT product_ibfk_1
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID)
ON DELETE CASCADE;


